#!/usr/bin/env bash
# cline-rotate — supervisor for the Cline CLI.
# Automatically switches free models on "Daily free model limit reached",
# and switches to another account when all models in the rotation are exhausted.
#
# Usage:
#   ./cline-rotate.sh "prompt"            # act mode, auto-approve
#   ./cline-rotate.sh -p "prompt"         # plan mode
#   ./cline-rotate.sh --session <id> "prompt"
#   ./cline-rotate.sh                     # interactive: probe, then open a REPL
#   CLINE_ACCOUNTS_DIR=/path ./cline-rotate.sh "prompt"
#   CLINE_MODELS="a b c" ./cline-rotate.sh "prompt"
#   CLINE_EXTRA_ARGS="--timeout 600" ./cline-rotate.sh "prompt"
#
# Env:
#   CLINE_ACCOUNTS_DIR  accounts root        (default: ~/.cline/accounts)
#   CLINE_MODELS        space-separated model ids, first = preferred
#   CLINE_BIN           cline binary         (default: cline from PATH)
#   CLINE_RETRIES       --retries value      (default: 12)
#   CLINE_PROBE_TIMEOUT seconds per probe    (default: 45)
#   CLINE_MAX_ACCOUNT_ROUNDS account switch loop guard (default: number of accounts)
#   CLINE_LOG_DIR       where to write cline-rotate.log (default: $CLINE_ACCOUNTS_DIR/../logs)

set -uo pipefail

# ── Free-model rotation ───────────────────────────────────────────────────────
# The model list is generated by cline_Models_Free_Make.sh from the cline binary itself and
# ordered by your priority in models_4_rotattion.txt. This fallback is used only
# when those files are missing.
DEFAULT_MODELS=(
	"cline-free/deepseek-v4.1-flash"
	"cline-free/muse-spark-1.3-contributor"
	"z-ai/glm-5.3-flash"
	"cline-free/solar-pro4"
	"poolside/laguna-s-2.1:free"
)

ACCOUNTS_DIR="${CLINE_ACCOUNTS_DIR:-$HOME/.cline/accounts}"
CLINE_BIN="${CLINE_BIN:-cline}"
CLINE_RETRIES="${CLINE_RETRIES:-12}"
PROBE_TIMEOUT="${CLINE_PROBE_TIMEOUT:-45}"
LOG_DIR="${CLINE_LOG_DIR:-$ACCOUNTS_DIR/../logs}"
mkdir -p "$LOG_DIR" 2>/dev/null || true
ROTATE_LOG="$LOG_DIR/cline-rotate.log"

# Resolve the skill directory: works for direct invocation, PATH invocation,
# and symlinked wrappers (SKILL_DIR/cline-rotate.sh -> skill/cline/cline-rotate.sh).
SKILL_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" >/dev/null 2>&1 && pwd)"
if [[ -L "${BASH_SOURCE[0]}" ]]; then
	SKILL_DIR="$(cd "$(dirname "$(readlink -f "${BASH_SOURCE[0]}")")" >/dev/null 2>&1 && pwd)"
fi
MODELS_FILE="$SKILL_DIR/cline-models-free.txt"

clog() {
	printf '[%s] %s\n' "$(date '+%Y-%m-%d %H:%M:%S')" "$*" | tee -a "$ROTATE_LOG" 2>/dev/null ||
		printf '[%s] %s\n' "$(date '+%Y-%m-%d %H:%M:%S')" "$*"
}

# Read the free-model catalogue generated by cline_Models_Free_Make.sh. The ids in that file
# are exactly what `cline -m` accepts, so no name resolution is needed.
read_models() {
	while IFS= read -r line; do
		[[ -z "$line" || "$line" == \#* ]] && continue
		printf '%s\n' "${line%%$'\t'*}"
	done <"$MODELS_FILE"
}

if [[ -n "${CLINE_MODELS:-}" ]]; then
	# shellcheck disable=SC2206
	MODELS=(${CLINE_MODELS})
elif [[ -f "$MODELS_FILE" ]]; then
	# shellcheck disable=SC2206
	MODELS=($(read_models))
	if [[ ${#MODELS[@]} -eq 0 ]]; then
		clog "warning: $MODELS_FILE is empty, using built-in list"
		MODELS=("${DEFAULT_MODELS[@]}")
	fi
else
	MODELS=("${DEFAULT_MODELS[@]}")
	clog "warning: $MODELS_FILE missing, using built-in list"
	clog "         run $SKILL_DIR/cline_Models_Free_Make.sh to generate it"
fi

# An account is only usable if its configured model participates in the
# rotation. A stale/mismatched model (e.g. a paid one whose key was revoked)
# must not be trusted: the probe below pins a rotation model explicitly.
in_rotation() {
	local m="$1"
	for r in "${MODELS[@]}"; do [[ "$r" == "$m" ]] && return 0; done
	return 1
}

# ── Collect accounts ──────────────────────────────────────────────────────────
# An account is skipped when it has no providers.json at all, or when the model
# configured for it is not part of the rotation (stale/paid/revoked model).
ACCOUNTS=()
if [[ -d "$ACCOUNTS_DIR" ]]; then
	while IFS= read -r dir; do
		[[ -z "$dir" ]] && continue
		p="$ACCOUNTS_DIR/$dir/settings/providers.json"
		[[ -f "$p" ]] || continue
		configured="$(python3 -c "
import json
try:
    print(json.load(open('$p'))['providers']['cline']['settings'].get('model') or '')
except Exception:
    print('')
" 2>/dev/null)"
		if [[ -z "$configured" ]]; then
			clog "skip account [$dir]: no model configured in providers.json"
			continue
		fi
		if ! in_rotation "$configured"; then
			clog "skip account [$dir]: model '$configured' is outside the rotation"
			continue
		fi
		ACCOUNTS+=("$ACCOUNTS_DIR/$dir")
	done < <(ls -1 "$ACCOUNTS_DIR" 2>/dev/null)
fi

if [[ ${#ACCOUNTS[@]} -eq 0 ]]; then
	echo "cline-rotate: no accounts found under $ACCOUNTS_DIR" >&2
	echo "hint: CLINE_ACCOUNTS_DIR=/path/to/accounts $0 ..." >&2
	exit 3
fi

MAX_ACCOUNT_ROUNDS="${CLINE_MAX_ACCOUNT_ROUNDS:-${#ACCOUNTS[@]}}"

# ── Parse CLI args ────────────────────────────────────────────────────────────
MODE="act"
SESSION_ID=""
PROMPT=""
EXTRA_ARGS=()
while [[ $# -gt 0 ]]; do
	case "$1" in
	-p | --plan)
		MODE="plan"
		shift
		;;
	--session)
		SESSION_ID="${2:-}"
		shift 2
		;;
	--session=*)
		SESSION_ID="${1#*=}"
		shift
		;;
	-h | --help)
		sed -n '2,30p' "$0" | sed 's/^# \{0,1\}//'
		exit 0
		;;
	--)
		shift
		while [[ $# -gt 0 ]]; do
			PROMPT="${PROMPT:+$PROMPT }$1"
			shift
		done
		;;
	-*)
		EXTRA_ARGS+=("$1")
		shift
		;;
	*)
		PROMPT="${PROMPT:+$PROMPT }$1"
		shift
		;;
	esac
done
[[ -n "${CLINE_EXTRA_ARGS:-}" ]] && EXTRA_ARGS+=($CLINE_EXTRA_ARGS)

if [[ -z "$PROMPT" && -z "$SESSION_ID" ]]; then
	# No prompt = interactive REPL. We still probe first so the session opens on
	# a model that is not already over its daily cap.
	INTERACTIVE=1
else
	INTERACTIVE=0
fi

# ── Model limit detection ─────────────────────────────────────────────────────
# In non-interactive mode the CLI exits 1 AND prints the limit banner, so the
# exit code cannot be trusted — we match on the message text instead.
# Returns 0 (true)  => free-model limit hit, rotate to another model.
# Returns 1 (false) => genuine failure / success, do not burn the rotation.
is_model_limit() {
	local out="$1"
	[[ "$out" == *"Daily free model limit reached"* ]] ||
		[[ "$out" == *"today's free usage limit"* ]] ||
		[[ "$out" == *"INFERENCE_CAP_ERROR"* ]] ||
		[[ "$out" == *"Free model promotion ended"* ]]
}

# ── Probe one model: quick one-shot run to see if it answers ──────────────────
# Exit codes: 0 = model alive, 1 = model limit reached, 2 = account-level error.
probe_model() {
	local account_dir="$1" model="$2"
	local email
	email="$(python3 -c "
import json,sys
try:
    d=json.load(open('$account_dir/settings/providers.json'))
    print(d['providers']['cline']['settings']['auth']['metadata']['userInfo'].get('email','?'))
except Exception:
    print('?')
" 2>/dev/null)"

	local probe_prompt='answer with the single word: ok'
	local out rc
	out="$("$CLINE_BIN" --auto-approve false --retries 1 --timeout "$PROBE_TIMEOUT" \
		--data-dir "$account_dir" -m "$model" "$probe_prompt" 2>&1)"
	rc=$?

	if is_model_limit "$out"; then
		clog "  probe  model=$model account=$email -> LIMIT REACHED"
		return 1
	fi
	if [[ $rc -ne 0 ]]; then
		clog "  probe  model=$model account=$email -> ERROR rc=$rc"
		clog "         account-level failure, skipping whole account"
		return 2
	fi
	clog "  probe  model=$model account=$email -> OK"
	return 0
}

# ── Persist the winning model as the account default ──────────────────────────
save_model() {
	local account_dir="$1" model="$2"
	python3 - "$account_dir/settings/providers.json" "$model" <<'PY' 2>/dev/null || true
import json, sys
path, model = sys.argv[1], sys.argv[2]
with open(path) as f:
    d = json.load(f)
s = d["providers"]["cline"]["settings"]
if s.get("model") == model:
    sys.exit(0)
s["model"] = model
d["providers"]["cline"]["updatedAt"] = __import__("datetime").datetime.utcnow().isoformat() + "Z"
with open(path, "w") as f:
    json.dump(d, f, indent=2)
PY
	clog "  saved  model=$model as account default"
}

# ── Main ──────────────────────────────────────────────────────────────────────
ACCOUNT_IDX=0
ACCOUNT_DEAD=""
DEAD_MODELS=() # models confirmed dead in the current account
GLOBAL_DEAD=() # "model|account" pairs dead in this invocation
TOTAL_ATTEMPTS=0
((TOTAL_ATTEMPTS_MAX = ${#ACCOUNTS[@]} * ${#MODELS[@]} + 5))

while true; do
	((TOTAL_ATTEMPTS += 1))
	if ((TOTAL_ATTEMPTS > TOTAL_ATTEMPTS_MAX)); then
		clog "ABORT: loop guard triggered ($TOTAL_ATTEMPTS_MAX attempts) — possible infinite loop"
		echo "cline-rotate: aborted, loop guard" >&2
		exit 4
	fi

	ACCOUNT_DIR="${ACCOUNTS[$ACCOUNT_IDX]}"
	ACCOUNT_NAME="$(basename "$ACCOUNT_DIR")"
	clog "== account [$ACCOUNT_NAME] (round $TOTAL_ATTEMPTS)"

	model=""
	for m in "${MODELS[@]}"; do
		skip=0
		for d in "${DEAD_MODELS[@]:-}"; do [[ "$d" == "$m" ]] && skip=1 && break; done
		((skip)) && continue
		for g in "${GLOBAL_DEAD[@]:-}"; do [[ "$g" == "$m|$ACCOUNT_NAME" ]] && skip=1 && break; done
		((skip)) && continue
		probe_model "$ACCOUNT_DIR" "$m"
		case $? in
		0)
			model="$m"
			break
			;;
		1)
			DEAD_MODELS+=("$m")
			GLOBAL_DEAD+=("$m|$ACCOUNT_NAME")
			;;
		2)
			ACCOUNT_DEAD=1
			break
			;; # auth/broken account: skip it entirely
		esac
	done

	# ── Account dead or all its models exhausted: rotate to the next one ──────
	if [[ -z "$model" ]]; then
		if [[ -n "$ACCOUNT_DEAD" ]]; then
			clog "  account [$ACCOUNT_NAME] unusable (auth/error), skipping"
			ACCOUNT_DEAD=""
		else
			clog "  all ${#MODELS[@]} models exhausted on [$ACCOUNT_NAME]"
		fi
		DEAD_MODELS=()
		((ACCOUNT_IDX += 1))
		if ((ACCOUNT_IDX >= ${#ACCOUNTS[@]})); then
			clog "  end of account list — re-probing from the first account"
			ACCOUNT_IDX=0
			GLOBAL_DEAD=()
			sleep 2
		fi
		((MAX_ACCOUNT_ROUNDS -= 1))
		if ((MAX_ACCOUNT_ROUNDS <= 0)); then
			clog "ABORT: all accounts exhausted (tried ${#ACCOUNTS[@]} account(s), ${#MODELS[@]} model(s))"
			echo "cline-rotate: all accounts exhausted" >&2
			exit 5
		fi
		continue
	fi

	# ── Run the real task on the working model ─────────────────────────────────
	save_model "$ACCOUNT_DIR" "$model"

	local_args=(--auto-approve true --retries "$CLINE_RETRIES" --data-dir "$ACCOUNT_DIR")
	[[ "$MODE" == "plan" ]] && local_args+=(-p)
	[[ -n "$SESSION_ID" ]] && local_args+=(--id "$SESSION_ID")
	[[ ${#EXTRA_ARGS[@]} -gt 0 ]] && local_args+=("${EXTRA_ARGS[@]}")
	local_args+=(-m "$model")

	# Interactive: hand the terminal over to cline on a live model.
	if [[ "$INTERACTIVE" == "1" ]]; then
		clog "  shell  model=$model account=$ACCOUNT_NAME (interactive)"
		exec "$CLINE_BIN" "${local_args[@]}"
	fi

	clog "  run    model=$model account=$ACCOUNT_NAME prompt=${PROMPT:0:60}..."
	OUT="$("$CLINE_BIN" "${local_args[@]}" "$PROMPT" 2>&1)"
	RC=$?

	if is_model_limit "$OUT"; then
		clog "  limit hit mid-run on model=$model -> rotate"
		DEAD_MODELS+=("$model")
		GLOBAL_DEAD+=("$model|$ACCOUNT_NAME")
		continue
	fi

	printf '%s\n' "$OUT"
	if [[ $RC -ne 0 ]]; then
		clog "  done   rc=$RC model=$model"
	else
		clog "  done   rc=0 model=$model"
	fi
	exit "$RC"
done
