#!/usr/bin/env bash
# opencode-free — extract every free model the OpenCode Zen provider offers,
# and write it to opencode-models-free.txt.
#
# The free tier is decided by price, not by the id: `opencode models --verbose
# opencode` prints one `opencode/<id>` line followed by a JSON blob with
# `cost` and `status`. A model is free iff input+output cost == 0. This is how
# the paid `-nano` tiers are excluded even though their ids look similar.
#
# Sources, in order (first wins):
#   1. OC_BIN_OVERRIDE    explicit path to the real opencode binary
#   2. opencode from PATH (or the nvm fallback used by opencode-rotate.sh)
#   3. OC_FREE_MODELS_JSON escape hatch: a JSON file with the catalogue
#
# The catalogue is read WITHOUT account isolation (`opencode models` is a
# local listing, never a billable ask — see SKILL.md).
#
# Output:  .agents/skills/opencode/opencode-models-free.txt   (id, one per line)
# Exit codes: 0 ok · 1 opencode not found · 2 catalogue not found

set -uo pipefail

SKILL_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" >/dev/null 2>&1 && pwd)"
[[ -L "${BASH_SOURCE[0]}" ]] && SKILL_DIR="$(cd "$(dirname "$(readlink -f "${BASH_SOURCE[0]}")")" >/dev/null 2>&1 && pwd)"

MODELS_FILE="$SKILL_DIR/opencode-models-free.txt"

# ── Resolve the opencode binary ───────────────────────────────────────────────
OC_BIN="${OC_BIN_OVERRIDE:-}"
[[ -z "$OC_BIN" ]] && OC_BIN="$(command -v opencode 2>/dev/null || true)"
[[ -z "$OC_BIN" && -x "$HOME/.nvm/versions/node/v22.20.0/bin/opencode" ]] && OC_BIN="$HOME/.nvm/versions/node/v22.20.0/bin/opencode"
if [[ -z "$OC_BIN" ]]; then
	echo "opencode-free: opencode binary not found on PATH" >&2
	echo "hint: OC_BIN_OVERRIDE=/path/to/opencode $0" >&2
	exit 1
fi

# ── Extract the free-model catalogue ──────────────────────────────────────────
catalogue_raw=""
if [[ -n "${OC_FREE_MODELS_JSON:-}" && -f "${OC_FREE_MODELS_JSON:-}" ]]; then
	catalogue_raw="$(cat "$OC_FREE_MODELS_JSON")"
else
	catalogue_raw="$("$OC_BIN" models --verbose opencode 2>/dev/null | python3 -c '
import sys, json
lines = sys.stdin.read().splitlines()
i, out = 0, []
while i < len(lines):
    l = lines[i].strip()
    if l.startswith("opencode/") and i + 1 < len(lines) and lines[i + 1].lstrip().startswith("{"):
        seg = "\n".join(lines[i + 1:])
        depth = end = 0
        for j, c in enumerate(seg):
            if c == "{":
                depth += 1
            elif c == "}":
                depth -= 1
                if depth == 0:
                    end = j
                    break
        d = json.loads(seg[: end + 1])
        cost = d.get("cost") or {}
        if d.get("status") == "active" and cost.get("input") == 0 and cost.get("output") == 0:
            out.append({"id": l, "name": d.get("name", "")})
        i += 1 + seg[: end + 1].count("\n") + 1
    else:
        i += 1
print(json.dumps(out, ensure_ascii=False))
')"
fi

if [[ -z "$catalogue_raw" || "$catalogue_raw" == "[]" ]]; then
	echo "opencode-free: could not extract the free-model catalogue from opencode" >&2
	echo "hint: OC_FREE_MODELS_JSON=/path/catalogue.json $0" >&2
	exit 2
fi

# ── Write the catalogue file atomically ───────────────────────────────────────
CATALOGUE_TMP="$(mktemp)"
printf '%s' "$catalogue_raw" >"$CATALOGUE_TMP"
python3 - "$CATALOGUE_TMP" "$MODELS_FILE" <<'PY'
import json, os, sys
models = json.load(open(sys.argv[1]))
path = sys.argv[2]
header = [
    "# OpenCode free models - auto-generated by opencode_Models_Free_Make.sh",
    "# Source: `opencode models --verbose opencode` (models.dev table, provider opencode).",
    "# A model is free iff status=active and input+output cost == 0.",
    "# Do not edit by hand; re-run opencode_Models_Free_Make.sh after every opencode update.",
    "# Format: model id, one per line (no display names)",
]
lines = [m["id"] for m in models]
tmp = path + ".tmp"
with open(tmp, "w") as f:
    f.write("\n".join(header) + "\n")
    f.write("\n".join(lines) + "\n")
os.replace(tmp, path)
print("wrote %d free models -> %s" % (len(lines), path), file=sys.stderr)
PY
rm -f "$CATALOGUE_TMP"

cat "$MODELS_FILE"
